add_newline = false

[character]
success_symbol = '[ #](bold green)'
error_symbol = "[ x](bold red)"
vicmd_symbol = "[ V](bold green)"

[git_status]
disabled = false

[git_commit]
commit_hash_length = 7
tag_disabled = false
only_detached = false

[battery]
disabled = true

[python]
disabled = true

[cmake]
disabled = true

[directory]
read_only = "(read only)"

[git_metrics]
disabled = false
format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '
